<a href="https://colab.research.google.com/github/RatihParamita/dataMining/blob/main/Percobaan2Week16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report

In [3]:
iris = load_iris()
X = iris.data
y = iris.target

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
nlp = MLPClassifier(hidden_layer_sizes=(2,), max_iter=5000, alpha=0.01, solver='adam', random_state=42)
nlp.fit(X_train, y_train)

MLPClassifier(alpha=0.01, hidden_layer_sizes=(2,), max_iter=5000,
              random_state=42)

In [9]:
y_pred = nlp.predict(X_test)

In [10]:
accuracy = accuracy_score(y_test, y_pred)
print(f'Akurasi: {accuracy * 100}%')
print(classification_report(y_test, y_pred, target_names=iris.target_names))

Akurasi: 36.666666666666664%
              precision    recall  f1-score   support

      setosa       0.00      0.00      0.00        10
  versicolor       0.00      0.00      0.00         9
   virginica       0.55      1.00      0.71        11

    accuracy                           0.37        30
   macro avg       0.18      0.33      0.24        30
weighted avg       0.20      0.37      0.26        30



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [12]:
print("\nArsitektur Neural Network:")
print(f"Input Layer: {X_train.shape[1]} neurons")
for i, size in enumerate(nlp.hidden_layer_sizes):
  print(f"Hidden Layer:{i + 1}: {size} neurons")
print(f"Output Layer: {nlp.n_outputs_} neurons")
print(f"Fungsi Aktivasi: {nlp.activation}")


Arsitektur Neural Network:
Input Layer: 4 neurons
Hidden Layer:1: 2 neurons
Output Layer: 3 neurons
Fungsi Aktivasi: relu


In [14]:
print("\nBobot dan Bias:")
print("Bobot antara input dan hidden layer:")
print(nlp.coefs_[0])
print("Bobot antara hidden dan output layer:")
print(nlp.coefs_[1])
print("Bias dari hidden layer")
print(nlp.intercepts_[0])
print("Bias dari output layer")
print(nlp.intercepts_[1])


Bobot dan Bias:
Bobot antara input dan hidden layer:
[[ 0.29043092  0.37942107]
 [-0.11143083 -0.92803836]
 [-0.12502741  1.30316477]
 [-0.319365    3.00535738]]
Bobot antara hidden dan output layer:
[[-0.68226519  0.66971868  0.33982245]
 [-2.13634104 -0.01405818  0.64075203]]
Bias dari hidden layer
[-0.36447033  1.46672126]
Bias dari output layer
[ 1.66226276 -0.12257475 -2.92008277]
